swagger: "2.0"
info:
  title: Service Status
  description: Service for managing and monitoring services
  version: ""
host: localhost:6066
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      - https
  /v1/environment:
    get:
      tags:
      - environment
      summary: list environment
      description: List all environments
      operationId: environment#list
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/EnvironmentEnvironmentResponseCollection'
      schemes:
      - http
      - https
    post:
      tags:
      - environment
      summary: add environment
      description: adds a new environment and returns the url of where to retrieve
        it
      operationId: environment#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/EnvironmentAddRequestBody'
          required:
          - name
          - friendly
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
      - https
  /v1/environment/{key}:
    put:
      tags:
      - environment
      summary: update environment
      description: update an existing environment
      operationId: environment#update
      parameters:
      - name: key
        in: path
        description: used for update case of changing key, PUT /environment/key
        required: true
        type: string
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/EnvironmentUpdateRequestBody'
          required:
          - name
          - friendly
      responses:
        "204":
          description: No Content response.
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/EnvironmentUpdateNotFoundResponseBody'
            required:
            - message
            - name
      schemes:
      - http
      - https
definitions:
  EnvironmentAddRequestBody:
    title: EnvironmentAddRequestBody
    type: object
    properties:
      active:
        type: boolean
        description: is environment active
        default: true
        example: true
      friendly:
        type: string
        description: url friendly name of environment used for REST based operations
        example: development
        maxLength: 150
      key:
        type: string
        description: used for update case of changing key, PUT /environment/key
        example: Non vitae dicta.
      name:
        type: string
        description: Name of environment
        example: Production
        maxLength: 150
      sort:
        type: integer
        description: useful for sorting in UI
        default: 0
        example: 0
        minimum: 0
        maximum: 5000
    example:
      active: true
      friendly: development
      key: Omnis sed omnis perspiciatis earum nobis.
      name: Production
      sort: 0
    required:
    - name
    - friendly
  EnvironmentEnvironmentResponseCollection:
    title: 'Mediatype identifier: application/vnd.service-status.environment; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/EnvironmentResponse'
    description: ListResponseBody is the result type for an array of EnvironmentResponse
      (default view)
    example:
    - active: true
      created: "1996-12-19T16:39:57-08:00"
      friendly: development
      name: Production
      sort: 0
      updated: "1996-12-19T16:39:57-08:00"
    - active: true
      created: "1996-12-19T16:39:57-08:00"
      friendly: development
      name: Production
      sort: 0
      updated: "1996-12-19T16:39:57-08:00"
    - active: true
      created: "1996-12-19T16:39:57-08:00"
      friendly: development
      name: Production
      sort: 0
      updated: "1996-12-19T16:39:57-08:00"
  EnvironmentResponse:
    title: 'Mediatype identifier: application/vnd.service-status.environment; view=default'
    type: object
    properties:
      active:
        type: boolean
        description: is environment active
        default: true
        example: true
      created:
        type: string
        description: timestamp of when environment was created
        example: "1996-12-19T16:39:57-08:00"
        format: date-time
      friendly:
        type: string
        description: url friendly name of environment used for REST based operations
        example: development
        maxLength: 150
      name:
        type: string
        description: Name of environment
        example: Production
        maxLength: 150
      sort:
        type: integer
        description: useful for sorting in UI
        default: 0
        example: 0
        minimum: 0
        maximum: 5000
      updated:
        type: string
        description: timestamp of when environment was updated
        example: "1996-12-19T16:39:57-08:00"
        format: date-time
    description: EnvironmentResponse result type (default view)
    example:
      active: true
      created: "1996-12-19T16:39:57-08:00"
      friendly: development
      name: Production
      sort: 0
      updated: "1996-12-19T16:39:57-08:00"
    required:
    - name
    - friendly
  EnvironmentUpdateNotFoundResponseBody:
    title: EnvironmentUpdateNotFoundResponseBody
    type: object
    properties:
      message:
        type: string
        description: Message of error
        example: environment test not found
      name:
        type: string
        description: friendly name of environment
        example: Repellendus magnam est.
    description: Environment not found
    example:
      message: environment test not found
      name: Voluptas error officiis ut alias.
    required:
    - message
    - name
  EnvironmentUpdateRequestBody:
    title: EnvironmentUpdateRequestBody
    type: object
    properties:
      active:
        type: boolean
        description: is environment active
        default: true
        example: true
      friendly:
        type: string
        description: url friendly name of environment used for REST based operations
        example: development
        maxLength: 150
      name:
        type: string
        description: Name of environment
        example: Production
        maxLength: 150
      sort:
        type: integer
        description: useful for sorting in UI
        default: 0
        example: 0
        minimum: 0
        maximum: 5000
    example:
      active: true
      friendly: development
      name: Production
      sort: 0
    required:
    - name
    - friendly
